# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/wepiha/Documents/qt-amdgpu-fan-ctl/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 638)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/amd.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelGPUforCurrentProfileLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelGPUforCurrentProfileLabel.sizePolicy().hasHeightForWidth())
        self.labelGPUforCurrentProfileLabel.setSizePolicy(sizePolicy)
        self.labelGPUforCurrentProfileLabel.setObjectName("labelGPUforCurrentProfileLabel")
        self.horizontalLayout_3.addWidget(self.labelGPUforCurrentProfileLabel)
        self.comboBoxCardIndex = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxCardIndex.setObjectName("comboBoxCardIndex")
        self.comboBoxCardIndex.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBoxCardIndex)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelTemperatureLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTemperatureLabel.sizePolicy().hasHeightForWidth())
        self.labelTemperatureLabel.setSizePolicy(sizePolicy)
        self.labelTemperatureLabel.setMinimumSize(QtCore.QSize(90, 0))
        self.labelTemperatureLabel.setObjectName("labelTemperatureLabel")
        self.gridLayout_2.addWidget(self.labelTemperatureLabel, 0, 0, 1, 1)
        self.labelTemperature = QtWidgets.QLabel(self.centralwidget)
        self.labelTemperature.setMinimumSize(QtCore.QSize(60, 0))
        self.labelTemperature.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemperature.setObjectName("labelTemperature")
        self.gridLayout_2.addWidget(self.labelTemperature, 0, 1, 1, 1)
        self.labelCoreClockLabel = QtWidgets.QLabel(self.centralwidget)
        self.labelCoreClockLabel.setMinimumSize(QtCore.QSize(90, 0))
        self.labelCoreClockLabel.setObjectName("labelCoreClockLabel")
        self.gridLayout_2.addWidget(self.labelCoreClockLabel, 0, 2, 1, 1)
        self.labelCoreClock = QtWidgets.QLabel(self.centralwidget)
        self.labelCoreClock.setMinimumSize(QtCore.QSize(60, 0))
        self.labelCoreClock.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCoreClock.setObjectName("labelCoreClock")
        self.gridLayout_2.addWidget(self.labelCoreClock, 0, 3, 1, 1)
        self.labelPowerLabel = QtWidgets.QLabel(self.centralwidget)
        self.labelPowerLabel.setMinimumSize(QtCore.QSize(90, 0))
        self.labelPowerLabel.setObjectName("labelPowerLabel")
        self.gridLayout_2.addWidget(self.labelPowerLabel, 0, 4, 1, 1)
        self.labelPower = QtWidgets.QLabel(self.centralwidget)
        self.labelPower.setMinimumSize(QtCore.QSize(60, 0))
        self.labelPower.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPower.setObjectName("labelPower")
        self.gridLayout_2.addWidget(self.labelPower, 0, 5, 1, 1)
        self.labelFanSpeedLabel = QtWidgets.QLabel(self.centralwidget)
        self.labelFanSpeedLabel.setMinimumSize(QtCore.QSize(90, 0))
        self.labelFanSpeedLabel.setObjectName("labelFanSpeedLabel")
        self.gridLayout_2.addWidget(self.labelFanSpeedLabel, 1, 0, 1, 1)
        self.labelFanSpeed = QtWidgets.QLabel(self.centralwidget)
        self.labelFanSpeed.setMinimumSize(QtCore.QSize(60, 0))
        self.labelFanSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFanSpeed.setObjectName("labelFanSpeed")
        self.gridLayout_2.addWidget(self.labelFanSpeed, 1, 1, 1, 1)
        self.labelMemClockLabel = QtWidgets.QLabel(self.centralwidget)
        self.labelMemClockLabel.setMinimumSize(QtCore.QSize(90, 0))
        self.labelMemClockLabel.setObjectName("labelMemClockLabel")
        self.gridLayout_2.addWidget(self.labelMemClockLabel, 1, 2, 1, 1)
        self.labelMemClock = QtWidgets.QLabel(self.centralwidget)
        self.labelMemClock.setMinimumSize(QtCore.QSize(60, 0))
        self.labelMemClock.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMemClock.setObjectName("labelMemClock")
        self.gridLayout_2.addWidget(self.labelMemClock, 1, 3, 1, 1)
        self.labelVoltageLabel = QtWidgets.QLabel(self.centralwidget)
        self.labelVoltageLabel.setMinimumSize(QtCore.QSize(90, 0))
        self.labelVoltageLabel.setObjectName("labelVoltageLabel")
        self.gridLayout_2.addWidget(self.labelVoltageLabel, 1, 4, 1, 1)
        self.labelVoltage = QtWidgets.QLabel(self.centralwidget)
        self.labelVoltage.setMinimumSize(QtCore.QSize(60, 0))
        self.labelVoltage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVoltage.setObjectName("labelVoltage")
        self.gridLayout_2.addWidget(self.labelVoltage, 1, 5, 1, 1)
        self.labelFanProfileLabel = QtWidgets.QLabel(self.centralwidget)
        self.labelFanProfileLabel.setMinimumSize(QtCore.QSize(90, 0))
        self.labelFanProfileLabel.setObjectName("labelFanProfileLabel")
        self.gridLayout_2.addWidget(self.labelFanProfileLabel, 2, 0, 1, 1)
        self.labelFanProfileStatus = QtWidgets.QLabel(self.centralwidget)
        self.labelFanProfileStatus.setMinimumSize(QtCore.QSize(60, 0))
        self.labelFanProfileStatus.setStyleSheet("QLabel { background-color: green; color: white }")
        self.labelFanProfileStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFanProfileStatus.setObjectName("labelFanProfileStatus")
        self.gridLayout_2.addWidget(self.labelFanProfileStatus, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_3.addWidget(self.graphicsView, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelUpdateEveryLabel = QtWidgets.QLabel(self.centralwidget)
        self.labelUpdateEveryLabel.setObjectName("labelUpdateEveryLabel")
        self.horizontalLayout_2.addWidget(self.labelUpdateEveryLabel)
        self.spinBoxInterval = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxInterval.setMinimum(50)
        self.spinBoxInterval.setMaximum(5000)
        self.spinBoxInterval.setSingleStep(500)
        self.spinBoxInterval.setProperty("value", 2500)
        self.spinBoxInterval.setObjectName("spinBoxInterval")
        self.horizontalLayout_2.addWidget(self.spinBoxInterval)
        self.labelSLabel = QtWidgets.QLabel(self.centralwidget)
        self.labelSLabel.setObjectName("labelSLabel")
        self.horizontalLayout_2.addWidget(self.labelSLabel)
        self.checkBoxEnableLogging = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxEnableLogging.setCheckable(False)
        self.checkBoxEnableLogging.setObjectName("checkBoxEnableLogging")
        self.horizontalLayout_2.addWidget(self.checkBoxEnableLogging)
        spacerItem = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonAdd = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAdd.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdd.sizePolicy().hasHeightForWidth())
        self.pushButtonAdd.setSizePolicy(sizePolicy)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout_2.addWidget(self.pushButtonAdd)
        self.pushButtonRemove = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRemove.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRemove.sizePolicy().hasHeightForWidth())
        self.pushButtonRemove.setSizePolicy(sizePolicy)
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.horizontalLayout_2.addWidget(self.pushButtonRemove)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonClose = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.gridLayout.addWidget(self.pushButtonClose, 0, 2, 1, 1)
        self.pushButtonSave = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.gridLayout.addWidget(self.pushButtonSave, 0, 1, 1, 1)
        self.pushButtonEnable = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEnable.setCheckable(True)
        self.pushButtonEnable.setChecked(False)
        self.pushButtonEnable.setObjectName("pushButtonEnable")
        self.gridLayout.addWidget(self.pushButtonEnable, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 4, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 85))
        self.plainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_3.addWidget(self.plainTextEdit, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "amdgpu-fan-ctl"))
        self.labelGPUforCurrentProfileLabel.setText(_translate("MainWindow", "GPU for Current Profile:"))
        self.comboBoxCardIndex.setItemText(0, _translate("MainWindow", "0"))
        self.labelTemperatureLabel.setText(_translate("MainWindow", "Temperature"))
        self.labelTemperature.setText(_translate("MainWindow", "..."))
        self.labelCoreClockLabel.setText(_translate("MainWindow", "Core Clock"))
        self.labelCoreClock.setText(_translate("MainWindow", "..."))
        self.labelPowerLabel.setText(_translate("MainWindow", "Power"))
        self.labelPower.setText(_translate("MainWindow", "..."))
        self.labelFanSpeedLabel.setText(_translate("MainWindow", "Fan Speed"))
        self.labelFanSpeed.setText(_translate("MainWindow", "..."))
        self.labelMemClockLabel.setText(_translate("MainWindow", "Core Clock"))
        self.labelMemClock.setText(_translate("MainWindow", "..."))
        self.labelVoltageLabel.setText(_translate("MainWindow", "Voltage"))
        self.labelVoltage.setText(_translate("MainWindow", "..."))
        self.labelFanProfileLabel.setText(_translate("MainWindow", "Fan Control"))
        self.labelFanProfileStatus.setText(_translate("MainWindow", "..."))
        self.labelUpdateEveryLabel.setText(_translate("MainWindow", "Update Every:"))
        self.labelSLabel.setText(_translate("MainWindow", "ms"))
        self.checkBoxEnableLogging.setText(_translate("MainWindow", "Enable Logging"))
        self.pushButtonAdd.setText(_translate("MainWindow", "+"))
        self.pushButtonRemove.setText(_translate("MainWindow", "-"))
        self.pushButtonClose.setText(_translate("MainWindow", "Close"))
        self.pushButtonSave.setText(_translate("MainWindow", "Save"))
        self.pushButtonEnable.setText(_translate("MainWindow", "Enable"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "WARNING: THIS SOFTWARE DOES NOT INCLUDE A WARRANTY OF ANY KIND. ENABLE MANUAL FAN CONTROL AT YOUR OWN RISK. Also note that many devices will limit the lowest possible fan speed and may not allow for control below that threshold. "))

from pyqtgraph import PlotWidget
